version: 2.1

parameters:
  l1_mainnet_rpc_url:
    type: string
    default: "https://ci-mainnet-l1.optimism.io"
  l1_goerli_rpc_url:
    type: string
    default: "https://ci-goerli-l1.optimism.io"
  l1_sepolia_rpc_url:
    type: string
    default: "https://ci-sepolia-l1.optimism.io"
  l2_mainnet_rpc_url:
    type: string
    default: "https://mainnet.optimism.io"
  l2_goerli_rpc_url:
    type: string
    default: "https://goerli.optimism.io"
  l2_sepolia_rpc_url:
    type: string
    default: "https://sepolia.optimism.io"
  time_diff_threshold:
    type: integer
    default: 5

jobs:
  check_sepolia_rpc_endpoints:
    docker:
      - image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:latest
    steps:
      - checkout
      - run:
          name: Install JQ
          command: sudo apt-get update && sudo apt-get install jq
      - run:
          name: Check Sepolia RPC Endpoints
          command: |
            if ops/verify_geth_endpoint.sh "<< parameters.l1_sepolia_rpc_url >>" $TIME_DIFF_THRESHOLD && \
               ops/verify_geth_endpoint.sh "<< parameters.l2_sepolia_rpc_url >>" $TIME_DIFF_THRESHOLD; then
              echo "Both RPC endpoints are up to date and not syncing."
              echo "<< parameters.ethereum_rpc_url >>" > /tmp/l1_sepolia_rpc_url
              echo "<< parameters.optimism_rpc_url >>" > /tmp/l2_sepolia_rpc_url
            else
              echo "One or both of the RPC endpoints failed the checks."
              exit 1
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
            - l1_sepolia_rpc_url
            - l2_sepolia_rpc_url
  check_goerli_rpc_endpoints:
    docker:
      - image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:latest
    steps:
      - checkout
      - run:
          name: Install JQ
          command: sudo apt-get update && sudo apt-get install jq
      - run:
          name: Check Goerli RPC Endpoints
          command: |
            if ops/verify_geth_endpoint.sh "<< parameters.ethereum_rpc_url >>" $TIME_DIFF_THRESHOLD && \
               ops/verify_geth_endpoint.sh "<< parameters.optimism_rpc_url >>" $TIME_DIFF_THRESHOLD; then
              echo "Both RPC endpoints are up to date and not syncing."
              echo "<< parameters.ethereum_rpc_url >>" > /tmp/l1_goerli_rpc_url
              echo "<< parameters.optimism_rpc_url >>" > /tmp/l2_goerli_rpc_url
            else
              echo "One or both of the RPC endpoints failed the checks."
              exit 1
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
            - l1_goerli_rpc_url
            - l2_goerli_rpc_url
  check_mainnet_rpc_endpoints:
    docker:
      - image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:latest
    steps:
      - checkout
      - run:
          name: Install JQ
          command: sudo apt-get update && sudo apt-get install jq
      - run:
          name: Check Mainnet RPC Endpoints
          command: |
            if ops/verify_geth_endpoint.sh "<< parameters.ethereum_rpc_url >>" $TIME_DIFF_THRESHOLD && \
               ops/verify_geth_endpoint.sh "<< parameters.optimism_rpc_url >>" $TIME_DIFF_THRESHOLD; then
              echo "Both RPC endpoints are up to date and not syncing."
              echo "<< parameters.ethereum_rpc_url >>" > /tmp/l1_mainnet_rpc_url
              echo "<< parameters.optimism_rpc_url >>" > /tmp/l2_mainnet_rpc_url
            else
              echo "One or both of the RPC endpoints failed the checks."
              exit 1
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
            - l1_mainnet_rpc_url
            - l2_mainnet_rpc_url
  # TODO: remove/replace when there are real consumers of the RPC URLs
  example_mainnet_job:
    docker:
      - image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:latest
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Use RPC URLs
          command: |
            if [ -f /tmp/l1_mainnet_rpc_url ] && [ -f /tmp/l2_mainnet_rpc_url ]; then
              L1_RPC_URL=$(cat /tmp/l1_mainnet_rpc_url)
              L2_RPC_URL=$(cat /tmp/l2_mainnet_rpc_url)
              echo "L1 RPC URL: $L1_RPC_URL"
              echo "L2 RPC URL: $L2_RPC_URL"
              # Use L1_RPC_URL and L2_RPC_URL here.
            else
              echo "Required RPC URLs are not available."
              exit 1
            fi
          

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - check_rpc_endpoints
      - example_mainnet_job:
          requires:
            - check_mainnet_rpc_endpoints
